name: FES
channels:
  - conda-forge
  - defaults
dependencies:
  - binutils # [not win]
  - boost-cpp
  - cartopy
  - cmake
  - cxx-compiler
  - eigen
  - gtest
  - make # [not win]
  - markdown
  - matplotlib
  - netcdf4
  - pytest
  - pyyaml
  - setuptools_scm
  - sphinx
  - sphinx-book-theme
  - sphinx-gallery
